### ISSUE TITLE
option to disable internal screen when docked

### ISSUE THREAD

**Issue by 1resu** [martin-ueding/thinkpad-scripts#103]
Hi,

it would be nice to have an option to disable the internal screen (LVDS1) when the thinkpad is docked, so that only a external screen is activated.

**Comment by martin-ueding** [comment]
I implemented an option for you in [feature/disable-internal-GH-103](https://github.com/martin-ueding/thinkpad-scripts/compare/develop...feature/disable-internal-GH-103).

So far, I do not quite understand why you want/need this option. You have one additional display attached and want to disable the internal screen such that the external display is the only one used?

Could you please check out this feature branch and install it, then test whether it does what you want? If you cannot do that, please let me know how you installed the regular version of this, then I'll try to cook something for you.

**Comment by 1resu** [comment]
Wow! Thanks for your work on this issue.

It works like expected. I only want to use my external screen when the notebook is docked because I don't need a two screen solution. Just my preference...
