### ISSUE TITLE
thinkpad-dock-hook crashed + double mouse cursor after screen rotation

### ISSUE THREAD

**Issue by chepec** [martin-ueding/thinkpad-scripts#104]
I installed thinkpad-scripts from the PPA on a fresh install of Ubuntu Gnome 14.04.2 on a Thinkpad X230T (64-bit machine) and experienced two bugs that appear to be linked (in that solving one apparently solved the other, too). Posting this for future reference.

After reboot (and on login) I got standard Ubuntu error message "Ubuntu 14.04 has experienced an internal error" with the following details:

Executable path: /usr/bin/thinkpad-dock-hook
Package: thinkpad-scripts 4.1.5-0ubuntu1 [origin: LP-PPA-martin-ueding-stable]
ProblemType: Crash
Title: thinkpad-dock-hook crashed with TypeError in wrapper(): sequence item 2: expected str instance, NoneType found

Plus some more details, but I'll spare you. I then tested to rotate the screen (physically) and the orientation rotated 90 degrees (I was hoping for a 180 flip, but I'll settle for a rotation). Nice! Upon returning the screen to its normal orientation, the cursor was observed to have a companion (to the right of it, and rotated 90 degrees). Very similar (perhaps identical) to these bug reports: 
https://bugs.launchpad.net/ubuntu/+source/xserver-xorg-video-intel/+bug/1376760
https://bugs.launchpad.net/ubuntu/+source/xserver-xorg-video-intel-lts-utopic/+bug/1443345
https://bugs.launchpad.net/ubuntu/+source/xorg/+bug/1393169

**Comment by chepec** [comment]
The "double mouse cursor"-problem was apparently fixed upstream in a [proposed package](https://launchpad.net/ubuntu/+source/xserver-xorg-video-intel/2:2.99.914-1~exp1ubuntu4.5), so I [followed these instructions](https://wiki.ubuntu.com/Testing/EnableProposed) and installed it and was surprised to find that not only had the "double cursor"-bug disappeared, but the thinkpad-dock-hook issue as well.

**Comment by jturner314** [comment]
@chepec I'm glad to hear that you were able to resolve the issue. By the way, if you'd like a 180 degree flip when you rotate the screen, you can create a config file that sets `default_rotation = flip` in the `[rotate]` section. [The docs](https://thinkpad-scripts.readthedocs.org/en/latest/man/thinkpad-rotate.1.html#config) provide the details.

**Comment by martin-ueding** [comment]
The older versions of Ubuntu do not get newer versions of thinkpad-scripts since there was one version which needs at least a certain version of `udev`. Therefore I stopped making backports and just package it for the version of Ubuntu that I currently use.

Other than that, this can probably be closed?

**Comment by chepec** [comment]
Yepp, go ahead and close this one. Appreciate the help.
