### ISSUE TITLE
Rotated on boot-up

### ISSUE THREAD

**Issue by kasbah** [martin-ueding/thinkpad-scripts#109]
Currently my x220 boots into Unity rotated anti-clockwise by one. Not sure where to change that. I am using Ubuntu 14.04 with the latest package from PPA (4.1.5-0ubuntu1). My `~/.config/thinkpad-scripts/config.ini`:

~~~
[rotate]
default_rotation=half
[vkeyboard]
program=onboard
~~~

**Comment by kasbah** [comment]
This is not an issue with thinkpad-rotate but with "GNOME assistive technology" which was enabled by the Onboard keyboard when selecting "auto show when editing text". 

The workaround is to disable assistive technologies (`gconftool-2 --type bool --set /desktop/gnome/interface/accessibility false`) re-login, then re-enable the option in Onboard (re-enabling assistive technologies) and then stay away from the rotate button on screen. 

https://bugs.launchpad.net/ubuntu/+source/gnome-control-center/+bug/1174830

**Comment by martin-ueding** [comment]
Interesting! I have a `thinkpad-rotate normal` in my startup scripts such that I always start with normal orientation when booting the computer. KDE remembers the screen orientation which is something that I do not want in every case.

**Comment by kasbah** [comment]
Well, now I put `thinkpad-rotate half` in a startup script because I am hoping to leave it mostly in tablet mode. But it gets _very_ confused when it's not in tablet mode, flipping exactly the wrong way when I put it in tablet mode and only correcting itself when turned back again. 

I might give KDE a go as well, I think I wrongly assumed Unity was built more for touch interfaces in mind.

**Comment by martin-ueding** [comment]
I currently cannot decide between Awesome WM (great tiling support) and KDE (things just work). I used them together, but KDE 5 is not really compatible with Awesome WM any more.

One problem with `thinkpad-rotate half` is that it is not idempotent. If it is already flipped, it will flip it back. If you need that, I could add a `--force-direction` option or so such that it will do what you told it to. Currently it tries to be clever and rotates back when the same direction is supplied twice. That way a button mapping will act as a toggle and you do not need two buttons to rotate it and get it back to normal. For a script it might be handy to force some state.

**Comment by kasbah** [comment]
>I could add a --force-direction option

That would be really good, yeah. Thanks for making this project by the way!

P.S. I had a brief look at KDE but it doesn't seem to get the screen rotation right either and doesn't seem very touch friendly without a lot of customization. I am really looking for an experience where I avoid switching to laptop mode as much as possible. I think I will stick to Unity after all.

**Comment by martin-ueding** [comment]
I added the option, it is shipping in version 4.6.0. It is already pushed and is in the building queue as a Ubuntu package for Vivid on Launchpad right now.

KDE does not seem to be that touch friendly, that is correct. They have the netbook theme for their GUI. There is Plasma Active, but I think that is only for mobile devices or so. I am not sure whether this can be run on a touch enabled laptop.

**Comment by kasbah** [comment]
Is it possible to configure this through config.ini?

**Comment by martin-ueding** [comment]
There is no configuration for this yet, this is just a command line option for `thinkpad-rotate`. What kind of option would you like? Something like `force-direction = true` that would always force any rotation given?
