### ISSUE TITLE
thinkpad-rotate-acpi-hook not working on X230

### ISSUE THREAD

**Issue by effello** [martin-ueding/thinkpad-scripts#114]
I tried to install everything as shown in your docs. Tried it through apt-get and compiled it myself. I checked the thinkpad-rotate-acpi-hook-2 and it should totally fits my needs. But as I turn my screen nothing happends. Need help please!!

**Comment by martin-ueding** [comment]
I have a similar problem on Fedora 23, the hook is installed but it does not actually rotate the screen. This is something I definitely want to fix as it annoys me as well. Problem is that I have three exams within the next three weeks and I do not have the capacity to drill down on that problem right now.

For the meantime I would suggest that you bind `thinkpad-rotate` to one of the hardware buttons. That is my current workaround, it is annoying but at least it works. Then after the last exam on 2016-02-23 I will take a look at this problem.

**Comment by effello** [comment]
I'm trying but the second thing that I found was that those Buttons under my screen don't work. The one with the circle on it is recognised but the other, which is normally use for screen rotation doesn't work.... How can I edit scripts the thinkpad-rotate so that it does not turn of my mouse or the pen when rotating to tablet mode?

**Comment by martin-ueding** [comment]
Regarding the extra button you can look at the following article: https://thinkpad-scripts.readthedocs.org/en/latest/guides/additional-keys.html

> How can I edit scripts the thinkpad-rotate so that it does not turn of my mouse or the pen when rotating to tablet mode? 

I do not understand your question, really. So you want to rotate the content of the screen but have the mouse and pen as they are? That would mean that all your motions would be turned around, pushing your mouse left would move the cursor right. Is that what you want?

Or is the rotation of the pen not working? That might also happen if the name of the input devices is wrong in our configuration and we would need to update that.

**Comment by effello** [comment]
No the Mouse and the pen is disappled after rotation

**Comment by martin-ueding** [comment]
They disappear? That is indeed very strange! What distribution and desktop environment do you use?

**Comment by effello** [comment]
Sorry don't know what that was but after some flipping it's working as it should also the pen does work. Thanks a lot for your help.

**Comment by martin-ueding** [comment]
The rotation on the hardware event now also works? If so, this issue can be closed?

**Comment by effello** [comment]
No that's still a problem I'm working on if I find something I let you know.

**Comment by martin-ueding** [comment]
So the manual rotation works as desired. The automatic rotation with the hardware event does not work at all?

**Comment by effello** [comment]
That's it manual rotation works fine. At first I had some "Unable to get graphical user" errors but they suddenly disappear. "service acpid status" has no errors now but still the hook does not work.

**Comment by martin-ueding** [comment]
What distribution are you on? Do you have SELinux active? If so, that is probably preventing the hardware hook from doing its job (see #116).

**Comment by martin-ueding** [comment]
I guess there is no interest in this any more.
