### ISSUE TITLE
thinkpad-dock will crash if no cable connection is configured

### ISSUE THREAD

**Issue by PJaros** [martin-ueding/thinkpad-scripts#121]
Dockinng my Thinpad x220t to my docking station will result in thinkpad-dock and thinkpad-dock-hook to crash. 
To find the cause of it, I have run this command while still beeing docked. 

```
$ thinkpad-dock on
Fehler: Aktivierung der Verbindung ist gescheitert: No suitable device found for this connection.
Traceback (most recent call last):
  File "/usr/bin/thinkpad-dock", line 9, in <module>
    load_entry_point('thinkpad-scripts==4.7.3', 'console_scripts', 'thinkpad-dock')()
  File "/usr/lib/python3/dist-packages/tps/dock.py", line 232, in main
    dock(desired, config)
  File "/usr/lib/python3/dist-packages/tps/dock.py", line 164, in dock
    tps.network.restart(connection_to_restart)
  File "/usr/lib/python3/dist-packages/tps/network.py", line 141, in restart
    tps.check_call(['nmcli', 'con', 'up', 'id', connection], logger)
  File "/usr/lib/python3/dist-packages/tps/__init__.py", line 139, in wrapper
    return function(command, *args, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['nmcli', 'con', 'up', 'id', 'Kabelnetzwerkverbindung 1']' returned non-zero exit status 4
```

Calling nmcli directly will result with this:
```
$ nmcli con up id "Kabelnetzwerkverbindung 1"
Fehler: Aktivierung der Verbindung ist gescheitert: No suitable device found for this connection.

```
I suspect this due the fact that either:
- The dockingstation has no ethernet connection
- The x220 ist freshly installed and the cable-connection was never used an thus, somehow, not complete setup.

**Comment by martin-ueding** [comment]
The easiest solution might be to set `network.restart_connection` to `false`, perhaps use that as the new default. Then this part of the code will not be executed. But perhaps you do want to have this restarting?

The name “Kabelnetzwerkverbindung 1” seems to come from your system. Is it listed in the output of `nmcli --terse --fields NAME,TYPE con show`? If there was no connection, then I believe it should not be tried to activate it. Perhaps there is indeed some wired connection that has not been configured. In that case this program here should be able to recover from that somehow.

On my laptop it finds the connection `enp0s25` and then is able to activate it without a problem.

What should we do? Just ignore errors that occur from the restarting process and move on in the execution of the script?

**Comment by jturner314** [comment]
> Just ignore errors that occur from the restarting process and move on in the execution of the script

That would be my preference because I often use `thinkpad-dock on` when I'm just connecting to an external display in my office (without the docking station and wired connection).

I propose changing `tps.check_call` to `tps.call` in `tps.network.restart` and maybe add `logger.warning` (or `logger.error`?) if the exit code is nonzero.

**Comment by martin-ueding** [comment]
I have use an `except` to catch the exception at that point and log a warning.

Shall we change the default of `network.restart_connection` to `false` as well?

**Comment by jturner314** [comment]
Thanks for changing it into a warning.

I don't think we should change the default because, since the error is now a warning, a failure doesn't interfere with the operation of the script. It may be helpful to mention in the warning message that `network.restart_connection` can be disabled for anyone who wants to get rid of the warning. If we do change the default, I think it should be part of a major release, because there may be people who depend on the current behavior.

**Comment by martin-ueding** [comment]
This has been sitting in my inbox for too long, sorry! I have now created a release 4.7.5 for this. It is uploaded to the Open Build Service and should build for Fedora 24 and Fedora 25 now. I am not sure which openSUSE distribution I should target.

@PJaros: What distribution do you use? If it is Ubuntu, which version should I upload that fix for?

**Comment by PJaros** [comment]
@martin-ueding 
```
$ uname -a
Linux ThinkPad04 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by martin-ueding** [comment]
Okay, then I will try to package the next release for Ubuntu 16.04 such that you can just install the Ubuntu package.

**Comment by martin-ueding** [comment]
I have now packaged it for Ubuntu and it seems to be available in the PPA.
