### ISSUE TITLE
Build fails on arch linux from AUR

### ISSUE THREAD

**Issue by Koeng101** [martin-ueding/thinkpad-scripts#122]
Hello,

I am trying to build thinkpad-scripts from the AUR (arch user repository). I've install all the dependencies, and now am trying to build this package. However, I get this error message- (I am installing using aura, it has the same error with normal installation)
```
aura >>= Determining dependencies...'
aura >>= AUR Packages:
thinkpad-scripts

aura >>= Continue? [Y/n] 
aura >>= Building `thinkpad-scripts`...
aura >>= Well, building `thinkpad-scripts` failed.
aura >>= Dumping makepkg output in 3.. 2.. 1..
==> Making package: thinkpad-scripts 4.7.4-1 (Mon Dec 12 10:00:54 UTC 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading v4.7.4.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   138    0   138    0     0    357      0 --:--:-- --:--:-- --:--:--   358
100  220k  100  220k    0     0   183k      0  0:00:01  0:00:01 --:--:--  647k
==> Validating source files with sha256sums...
    v4.7.4.tar.gz ... Passed
==> Extracting sources...
  -> Extracting v4.7.4.tar.gz with bsdtar
==> Starting build()...
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 11, in <module>
    load_entry_point('Sphinx==1.5', 'console_scripts', 'sphinx-build')()
  File "/usr/lib/python3.5/site-packages/sphinx/__init__.py", line 66, in main
    sys.exit(build_main(argv))
  File "/usr/lib/python3.5/site-packages/sphinx/__init__.py", line 76, in build_main
    from sphinx import cmdline
  File "/usr/lib/python3.5/site-packages/sphinx/cmdline.py", line 23, in <module>
    from sphinx.application import Sphinx
  File "/usr/lib/python3.5/site-packages/sphinx/application.py", line 32, in <module>
    from sphinx.config import Config
  File "/usr/lib/python3.5/site-packages/sphinx/config.py", line 21, in <module>
    from sphinx.util.i18n import format_date
  File "/usr/lib/python3.5/site-packages/sphinx/util/i18n.py", line 20, in <module>
    import babel.dates
  File "/usr/lib/python3.5/site-packages/babel/dates.py", line 29, in <module>
    from babel.util import UTC, LOCALTZ
  File "/usr/lib/python3.5/site-packages/babel/util.py", line 19, in <module>
    from babel import localtime
  File "/usr/lib/python3.5/site-packages/babel/localtime/__init__.py", line 74, in <module>
    LOCALTZ = get_localzone()
  File "/usr/lib/python3.5/site-packages/babel/localtime/__init__.py", line 70, in get_localzone
    return _get_localzone()
  File "/usr/lib/python3.5/site-packages/babel/localtime/_unix.py", line 136, in _get_localzone
    return pytz.tzfile.build_tzinfo('local', tzfile)
  File "/usr/lib/python3.5/site-packages/pytz/tzfile.py", line 30, in build_tzinfo
    typecnt, charcnt) =  unpack(head_fmt, fp.read(head_size))
struct.error: unpack requires a bytes object of length 44
make[1]: *** [makefile:26: html] Error 1
make: *** [makefile:11: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

cd desktop && make
make[1]: Entering directory '/var/cache/pacman/pkg/thinkpad-scripts18605/thinkpad-scripts/src/thinkpad-scripts-4.7.4/desktop'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/var/cache/pacman/pkg/thinkpad-scripts18605/thinkpad-scripts/src/thinkpad-scripts-4.7.4/desktop'
cd doc && make
make[1]: Entering directory '/var/cache/pacman/pkg/thinkpad-scripts18605/thinkpad-scripts/src/thinkpad-scripts-4.7.4/doc'
sphinx-build -b html -d _build/doctrees  . _build/html
make[1]: Leaving directory '/var/cache/pacman/pkg/thinkpad-scripts18605/thinkpad-scripts/src/thinkpad-scripts-4.7.4/doc'
```

**Comment by jturner314** [comment]
I just double-checked that it builds correctly on my system, so something strange is happening on your system specifically. Based on the traceback, it looks like the docs are failing to build correctly with `sphinx-build` because `babel` is failing to get the local timezone. (I expect this is not specific to `thinkpad-scripts`.) Looking at the source code for `babel` and `pytz`, I'm suspicious that `/etc/localtime` exists on your system but is less than 44 bytes. That would cause this error.

Will you please post the output of
```bash
ls -l /etc/localtime
```
and
```bash
wc -c /etc/localtime
```
and
```bash
xxd /etc/localtime
```
?

**Comment by martin-ueding** [comment]
Thank you, @jturner314, for looking into that!

Just out of curiosity: Why do you, @Koeng101, want to build this package from source? Just to see whether it works? Or did something else not work for you?

**Comment by jturner314** [comment]
@martin-ueding The AUR is a repository of build instructions submitted by users for packages that aren't in the official repositories. It's similar to the BSD ports system, if you're familiar with that. To install a package from the AUR, you:

1. clone the build instructions (e.g. `git clone https://aur.archlinux.org/thinkpad-scripts.git`)
2. run `makepkg`, which downloads the source files and builds the package according to the build instructions
3. run `sudo pacman -U package.tar.xz` to install the built package

There are tools to automate this process for you, such as `aura`, but they always build the package from source (except for a few packages in the AUR which extract binaries from other distributions' packages instead). Binary packages are only available through the official repositories.

**Comment by martin-ueding** [comment]
A friend uses yaourt, I assumed that it would download binary packages.

One can set up an Arch repository on the open build service if that would be of any use.
-- 
http://martin-ueding.de/#pk_campaign=Email

Sent from my mobile, please excuse my brevity.

**Comment by Koeng101** [comment]
I fixed the local time and it compiled correctly. Thank you for the help jturner314, I appreciate it a lot!
