### ISSUE TITLE
Rotate hook does not rotate touch and pen input when using GNOME

### ISSUE THREAD

**Issue by DonHugo69** [martin-ueding/thinkpad-scripts#139]
- X230T
- Arch Linux
- Gnome 3.26.1 
- X11 session
- All updates applied

I am using the current thinkpad-scripts version from the AUR and set everything up according to the docs. The rotation hook is working, however after the screen has been rotated, the input is not. Moving the cursor up via the pen translates to left, etc. The same is true for the touch input. 
Invoking the rotation via calling thinkpad-rotate leads to the same result. 

```
tps.config    DEBUG    ----------------------------------
tps.config    DEBUG    Program was started with arguments: ['/usr/bin/thinkpad-rotate', '-vv']
tps.config    DEBUG    Default configfile is /usr/lib/python3.6/site-packages/tps/default.ini.
tps.screen    DEBUG    subprocess “xrandr”
tps.screen    DEBUG    Screens available on this system are LVDS1.
tps.screen    DEBUG    Internal screen is determined to be LVDS1.
tps.screen    DEBUG    subprocess “xrandr -q --verbose”
tps           DEBUG    Converted “normal” to “Direction(xrandr='normal', xsetwacom='none', subpixel='rgb', physically_closed=False, rot_mat=[1, 0, 0, 0, 1, 0, 0, 0, 1])”.
tps.screen    INFO     Current rotation is “Direction(xrandr='normal', xsetwacom='none', subpixel='rgb', physically_closed=False, rot_mat=[1, 0, 0, 0, 1, 0, 0, 0, 1])”.
tps           DEBUG    Converted “right” to “Direction(xrandr='right', xsetwacom='cw', subpixel='vbgr', physically_closed=True, rot_mat=[0, 1, 0, -1, 0, 1, 0, 0, 1])”.
tps.rotate    INFO     Using default, setting to Direction(xrandr='right', xsetwacom='cw', subpixel='vbgr', physically_closed=True, rot_mat=[0, 1, 0, -1, 0, 1, 0, 0, 1])
tps           DEBUG    Command “/home/roland/.config/thinkpad-scripts/hooks/prerotate” not found.
tps.screen    DEBUG    subprocess “xrandr --output LVDS1 --rotate right”
tps.screen    DEBUG    subprocess “xrandr -q”
tps.input     DEBUG    Translation and scaling matrix: [[  1.00000   0.00000   0.00000 ][  0.00000   1.00000   0.00000 ][  0.00000   0.00000   1.00000 ]]
tps.input     DEBUG    Complete transformation matrix: [[  0.00000   1.00000   0.00000 ][ -1.00000   0.00000   1.00000 ][  0.00000   0.00000   1.00000 ]]
tps.config    DEBUG    Default configfile is /usr/lib/python3.6/site-packages/tps/default.ini.
tps.input     DEBUG    Using “Wacom ISD.*id=(\d+)” as regex to find Wacom devices.
tps.input     DEBUG    subprocess “xinput”
tps.input     INFO     Mapping and rotating all input devices.
tps.input     DEBUG    subprocess “xinput --list-props 10”
tps.input     DEBUG    Device 10 has property “Wacom Rotation”
tps.input     INFO     Device 10 has “Wacom Rotation” property, use xsetwacom.
tps.input     DEBUG    subprocess “xsetwacom set 10 rotate cw”
tps.input     DEBUG    subprocess “xsetwacom set 10 MapToOutput LVDS1”
tps.input     DEBUG    subprocess “xinput --list-props 11”
tps.input     DEBUG    Device 11 has property “Wacom Rotation”
tps.input     INFO     Device 11 has “Wacom Rotation” property, use xsetwacom.
tps.input     DEBUG    subprocess “xsetwacom set 11 rotate cw”
tps.input     DEBUG    subprocess “xsetwacom set 11 MapToOutput LVDS1”
tps.input     DEBUG    subprocess “xinput --list-props 16”
tps.input     DEBUG    Device 16 has property “Wacom Rotation”
tps.input     INFO     Device 16 has “Wacom Rotation” property, use xsetwacom.
tps.input     DEBUG    subprocess “xsetwacom set 16 rotate cw”
tps.input     DEBUG    subprocess “xsetwacom set 16 MapToOutput LVDS1”
tps.screen    DEBUG    subprocess “xrandr”
tps           DEBUG    Command “xfconf-query” not found.
tps           DEBUG    Command “gsettings” found.
tps.screen    DEBUG    subprocess “gsettings list-schemas”
tps.screen    DEBUG    subprocess “gsettings set org.gnome.settings-daemon.plugins.xsettings rgba-order vbgr”
tps.vkeyboard DEBUG    subprocess “pgrep kvkbd”
tps           DEBUG    Command “kvkbd” not found.
tps.vkeyboard WARNING  kvkbd is not installed
tps.input     DEBUG    subprocess “xinput list”
tps.input     DEBUG    subprocess “xinput set-prop 14 'Device Enabled' 0”
tps.input     DEBUG    subprocess “xinput list”
tps.input     DEBUG    subprocess “xinput set-prop 13 'Device Enabled' 0”
tps           DEBUG    Command “/home/roland/.config/thinkpad-scripts/hooks/postrotate” not found.
```

Furthermore it should be noted that the button to rotate the screen is working even without installing the thinkpad-scripts package and rotates the input properly. 
When I used KDE Plasma 5 before on the same machine, everything was working properly after installing thinkpad-scripts but the buttons did not work without manual keybindings. 

There is an old comment on the AUR page https://aur.archlinux.org/packages/thinkpad-scripts/
But I am not sure if and how they are related and I did not get the same error message.
Anything I can do to try to fix that issue?

**Comment by martin-ueding** [comment]
The thing with the comment on the AUR is just that the program crashes at some point because the subpixel anti-alias cannot be properly set. In this case one would just ignore this error or do some further diagnosis.

Regarding your error: It sounds like the devices were not properly found, but from the debug output it seems like this properly worked. I vaguely recall that we had some issue with the `xsetwacom` approach at some point and that one needed to use `xinput` to rotate.

You see the commented out `wacom_rotate_reset` call there. We had the problem that something else also rotated the input devices and therefore we needed to undo those changes to only keep our own.

```python
def map_rotate_all_input_devices(output, orientation):
    '''
    Maps all Wacom® devices.
    '''
    matrix = generate_xinput_coordinate_transformation_matrix(output,
                                                              orientation)
    wacom_device_ids = get_wacom_device_ids()

    logger.info('Mapping and rotating all input devices.')
    for device in wacom_device_ids:
        if has_device_property(device, 'Wacom Rotation'):
            logger.info('Device %d has “Wacom Rotation” property, use xsetwacom.', device)
            map_rotate_wacom_device(device, output, orientation)
        else:
            logger.info('Device %d does not have “Wacom Rotation” property, use xinput and try xsetwacom.', device)
            map_rotate_input_device(device, matrix)
            #wacom_rotate_reset(device)
```

So you could try the following:

- Locate the file `tps/input.py` on your system, should be somewhere in `/usr/lib/python3....`.
- Change `if has_device_property(device, 'Wacom Rotation'):` to `if False and has_device_property(device, 'Wacom Rotation'):` in order to deactivate that branch.
- Try the rotation again and post the debug output.

It should then try to use `xinput` only. If that does not work, also remove the comment in front of the `wacom_rotate_reset(device)` call.

Could you please also post the output of the following commands?

- `xrandr`
- `xinput`

**Comment by DonHugo69** [comment]
Thanks a lot! I changed the input.py in /usr/lib/python3.6/site-packages/tps and the input is now correct. It might useful to add it to the manual that this change might be necessary if using GNOME.
xinput:
```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ Wacom ISDv4 E6 Pen stylus               	id=10	[slave  pointer  (2)]
⎜   ↳ Wacom ISDv4 E6 Finger touch             	id=11	[slave  pointer  (2)]
⎜   ↳ Wacom ISDv4 E6 Pen eraser               	id=16	[slave  pointer  (2)]
⎜   ↳ TPPS/2 IBM TrackPoint                   	id=14	[slave  pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad              	id=13	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=8	[slave  keyboard (3)]
    ↳ Integrated Camera: Integrated C         	id=9	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=12	[slave  keyboard (3)]
    ↳ ThinkPad Extra Buttons                  	id=15	[slave  keyboard (3)]
```

xrandr:
```
Screen 0: minimum 8 x 8, current 1366 x 768, maximum 32767 x 32767
LVDS1 connected primary 1366x768+0+0 (normal left inverted right x axis y axis) 280mm x 160mm
   1366x768      60.02*+
   1280x720      60.00  
   1024x768      60.00  
   1024x576      60.00  
   960x540       60.00  
   800x600       60.32    56.25  
   864x486       60.00  
   640x480       59.94  
   720x405       60.00  
   680x384       60.00  
   640x360       60.00  
DP1 disconnected (normal left inverted right x axis y axis)
DP2 disconnected (normal left inverted right x axis y axis)
HDMI1 disconnected (normal left inverted right x axis y axis)
HDMI2 disconnected (normal left inverted right x axis y axis)
VGA1 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)

```

**Comment by jturner314** [comment]
I suspect that GNOME was setting `Coordinate Transformation Matrix`, while `thinkpad-scripts` was setting `Wacom Rotation` (via `xsetwacom`), and the two changes conflicted (i.e. the opposite of [this comment](https://github.com/martin-ueding/thinkpad-scripts/issues/117#issuecomment-209167909) in issue #117). It would be possible to confirm this by looking at the output of `xinput --list-props ID` after the broken rotation, where `ID` is the ID of the input device.

@martin-ueding We could add a config option for the user to enable/disable use of `Wacom Rotation` (`xsetwacom`). If the `Wacom Rotation` property is disabled or not available for the device, we could fall back to `Coordinate Transformation Matrix`.

**Comment by martin-ueding** [comment]
I would definitely like this to work out automatically. In the ideal case we do not need a configuration option and burden the user with it. The issue seems to bet that both the coordinate transformation matrix and the Wacom rotation are set.

Wouldn't it be sufficient to uncomment the reset after using the Wacom rotation? Alternative we could check whether the transformation matrix is already set correctly and skip the Wacom rotation?

**Comment by DonHugo69** [comment]
I followed @jturner314 and got the output of `xinput --list-props ID` 

before rotation:
```
Device 'Wacom ISDv4 E6 Pen stylus':
	Device Enabled (140):	1
	Coordinate Transformation Matrix (142):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
```

"broken" :
```
Device 'Wacom ISDv4 E6 Pen stylus':
	Device Enabled (140):	1
	Coordinate Transformation Matrix (142):	0.000000, 1.000000, 0.000000, -1.000000, 0.000000, 1.000000, 0.000000, 0.000000, 1.000000
```

"fixed":
```
Device 'Wacom ISDv4 E6 Pen stylus':
	Device Enabled (140):	1
	Coordinate Transformation Matrix (142):	0.000000, 1.000000, 0.000000, -1.000000, 0.000000, 1.000000, 0.000000, 0.000000, 1.000000
```

This looks identical to me (the fix works).

**Comment by martin-ueding** [comment]
Okay, so the issue is the following:

- thinkpad-scripts detects `xsetwacom` on your system and also that there is a special Wacom device property. Therefore it uses this to rotate.
- GNOME (or something else) also rotates the device, but using the transformation matrix for that.

Within thinkpad-scripts we can do the following:

1. Give the user the option to choose either the Wacom property or the transformation matrix. This would require effort on the user's part and also just parameterizes our (developer) ignorance of the other processes trying to rotate the screen.

2. Try to find out whether the transformation matrix has already been used by some other process when we get to the rotation logic in thinkpad-scripts. This is likely prone to a race condition.

3. Go back to always use the transformation matrix, even if there is a supported Wacom property. But I think there was also some issue with that.

So perhaps, after all, option 1 is the best one?

**Comment by martin-ueding** [comment]
So we will probably have to add another configuration option because we cannot reliably find out what is going on with the user's desktop environment?

**Comment by martin-ueding** [comment]
I have added the option. So @DonHugo69, please add the following to your configuration file:

```ini
[input]
use_xsetwacom_if_available = false
```

Then try again with `thinkpad-rotate flip -vv`. The output should now say that it cannot find the Wacom rotation property and therefore uses `xinput` to rotate. This should then just overwrite what GNOME is doing, effectively giving you the correct result.

If that does not help, please complain, we will re-open the issue.

**Comment by jturner314** [comment]
That config option looks good to me. I updated the package in the AUR.

**Comment by DonHugo69** [comment]
Sorry for the delay. No issues, works as intended. Thank you very much for your great support!

**Comment by martin-ueding** [comment]
Thank you for the kind words! You have made it easy to help by posting a lot of debug output, and we had this problem reported in the past as well, so it was an easy fix :-)
