### ISSUE TITLE
W530: Strange ACPI suspend events when docked on 433830U. Why?

### ISSUE THREAD

**Issue by mauzil** [martin-ueding/thinkpad-scripts#144]
Hi all.
I get strange ACPI events only when w530 is switched on over docking stations.
When Debian shows lightdm login screen, ACPI suspend events are thrown and W530 goes to suspend mode.
I push on power button in the docking station and the system restores.

This ACPI events are not throw if W530 is switched on outside docking.

**Comment by martin-ueding** [comment]
This sounds very weird indeed. I would think that thinkpad-scripts is not at fault because we do not (as far as I know) issue suspend commands. Does this also occur when thinkpad-scripts is not installed? Can you perhaps look into the syslog (perhaps `journalctl -u acpi` or so) and see whether there is something relevant there?

**Comment by mauzil** [comment]
Thank you for the answer.

The strange behaviours with suspend mode happens without 
thinkpad-scripts and only over the docking station.


Il 19/05/2018 17:45, Martin Ueding ha scritto:

**Comment by martin-ueding** [comment]
I see, so this has nothing to do with our code, it's just that we have some experience with ACPI and stuff.

You could check whether there are some ACPI hooks in the `/etc/acpi/events/` directory that look suspicious. Also one would need to look through the various systemd directories, I am not exactly sure where to look for possible hooks. Perhaps something is in the system log. Also with Debian I have seen some strange changes to upstream software, so unfortunately it *could* also be a Debian-made problem.

**Comment by mauzil** [comment]
Hi. There is the possibility to aviod that the system goes in  S3 state anymore?

**Comment by martin-ueding** [comment]
I suppose this is something that can be done with TLP. But why would you want to do that?

**Comment by mauzil** [comment]
Because I have a problem with W530 and docking station 433835U in dual monitor.
Very often with debian kernel 4.9.0 and nvidia driver, the workstation goes to S3 state before get the xdm login.
But only when the W530 is on the docking station.
So I'd like to disable S3 state to avoid unneeded suspend-to-ram
