### ISSUE TITLE
Internet Connection Required for Rotation

### ISSUE THREAD

**Issue by synackd** [martin-ueding/thinkpad-scripts#145]
I'm running a `systemd`-less version of Arch Linux called Artix on my ThinkPad X220 Tablet.
I found through some troubleshooting that
```bash
$ thinkpad-rotate
```
only works when I have an Internet connection. If not, running the command yields:
```python
Traceback (most recent call last):
  File "/usr/bin/thinkpad-rotate", line 11, in <module>
    load_entry_point('thinkpad-scripts==4.11.0', 'console_scripts', 'thinkpad-rotate')()
  File "/usr/lib/python3.6/site-packages/tps/rotate.py", line 26, in main
    options = _parse_args()
  File "/usr/lib/python3.6/site-packages/tps/rotate.py", line 237, in _parse_args
    tps.config.set_up_logging(options.verbose)
  File "/usr/lib/python3.6/site-packages/tps/config.py", line 214, in set_up_logging
    syslog = logging.handlers.SysLogHandler(**kwargs)
  File "/usr/lib/python3.6/logging/handlers.py", line 831, in __init__
    ress = socket.getaddrinfo(host, port, 0, socktype)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 1945, in shutdown
    h.close()
  File "/usr/lib/python3.6/logging/handlers.py", line 894, in close
    self.socket.close()
AttributeError: 'SysLogHandler' object has no attribute 'socket'
```
I'm not sure why the logger would need a socket to log locally...
Is this behavior intentional or is it my system? I'd rather not have to be connected to the Internet to rotate my screen. Thanks!

**Comment by martin-ueding** [comment]
Do you have a loopback network device configured? I am not sure, but it seems that the system log is accessed via a (local) network socket.

You can just set the configuration option `logging.syslog` to `false` and it won't try to log everything. That should fix the problem for you.

**Comment by synackd** [comment]
I'll try that!

I run `thinkpad-config` and see the option in there:
```ini
[logging]
syslog = true
```
but I don't see a config file in `~/.config/thinkpad-scripts` as stated in the docs. I also haven't found anything with `find`. Should I create one or is there a file elsewhere?

**Comment by martin-ueding** [comment]
That's all correct, you see the default config coming from the file which is installed system-wide. Just create your own at `~/.config/thinkpad-scripts` and you can overwrite options.

**Comment by synackd** [comment]
Creating `~/.config/thinkpad-scripts/config.ini` and adding:
```ini
[logging]
syslog = false
```
solved the problem.
However, is there any way I can keep syslogging in case I need to troubleshoot in the future?

**Comment by synackd** [comment]
I do have a loopback device set up:
```bash
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 brd 127.255.255.255 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
...
```

**Comment by martin-ueding** [comment]
Perhaps this works, but one would likely have to change the code. See `tps/config.py`, the function `set_up_logging`. There we create a new handle for the system log: `syslog = logging.handlers.SysLogHandler(**kwargs)`. From the [documentation](https://docs.python.org/3/library/logging.handlers.html#sysloghandler) it seems that one can change the connection type. I presume one would have to add more arguments to get it working on your system.

You can try to hard-code something that works on your system and then we can try to generalize this to a configuration option.

**Comment by synackd** [comment]
I will try that. I can either locally mess with it and update this issue with any successes or fork it. Shall I do the former?

**Comment by martin-ueding** [comment]
If you could fork and send a pull request, it would of course be the most comfortable!

**Comment by synackd** [comment]
I'll get right on it. Thanks for your help, Martin!

**Comment by synackd** [comment]
Pull request: [#146](https://github.com/martin-ueding/thinkpad-scripts/pull/146)

**Comment by martin-ueding** [comment]
I presume that you have solved your issue with the patch.
