### ISSUE TITLE
Having trouble understanding the rotate hooks

### ISSUE THREAD

**Issue by manderso7** [martin-ueding/thinkpad-scripts#149]
The documentation shows what to enter for a hooks.pre- and post-rotate, but I'm having trouble understanding where to enter this information:

https://thinkpad-scripts.readthedocs.io/en/latest/man/thinkpad-rotate.1.html#config

I have a config.ini with the example from the document, and have created ~/.config/thinkpad-scripts/hooks, but I don't know if I need a pre-rotate and post-rotate file, and if so, what to put in them. Can you explain further what's required?

This is on Ubuntu 19.10, with the scripts properly installed.

Thank you

**Comment by martin-ueding** [comment]
You only need those scripts if you want something to be run before or after the rotation. Just ignore those files, the scripts will work without them.

**Comment by manderso7** [comment]
Thanks, but I'm not sure how to get the scripts to run when I change the orientation of the screen on my x220t. I can change the orientation manually when I hit the button on the monitor, but not automatically when I rotate the screen.

**Comment by martin-ueding** [comment]
Did you install it such that all the system wide hooks also got installed? Unfortunately the installation takes a couple of steps.

**Comment by manderso7** [comment]
> Did you install it such that all the system wide hooks also got installed? Unfortunately the installation takes a couple of steps.

Unfortunately, I don't know if all the system-wide hooks were installed. I've installed manually using python3 setup.py install, as well as installed the latest deb from [launchpad](https://launchpad.net/~martin-ueding/+archive/ubuntu/stable/+packages?field.name_filter=thinkpad&field.status_filter=published&field.series_filter=)
however, even after restarting acpid, nothing happens when I rotate the screen. I'm still able to rotate the screen when clicking the rotate button.

**Comment by martin-ueding** [comment]
Installing from source *and* installing the Debian package will give you some sort of mess. Perhaps uninstall the Debian package and try the [installation instructions for a source install](https://thinkpad-scripts.readthedocs.io/en/latest/guides/getting-started.html#build-manually).

**Comment by manderso7** [comment]
Apologies for the confusion. I had tried these methods on different ubuntu installations, hoping one would work.
Currently I've installed from source, cloning the git repo, running make, sudo make install and then sudo ./setup.py install, and no errors in the output. I've restarted acpid, but nothing happens after rotating the screen or taking the laptop out of the dock.
Here's the output of the installation steps:
```
manderso@thinky:~/git/thinkpad-scripts$ make
cd desktop && make
make[1]: Entering directory '/home/manderso/git/thinkpad-scripts/desktop'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/manderso/git/thinkpad-scripts/desktop'
cd doc && make
make[1]: Entering directory '/home/manderso/git/thinkpad-scripts/doc'
/usr/share/sphinx/scripts/python3/sphinx-build -b html -d _build/doctrees  . _build/html
Running Sphinx v1.8.5
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
no targets are out of date.
build succeeded.

The HTML pages are in _build/html.
/usr/share/sphinx/scripts/python3/sphinx-build -b man -d _build/doctrees  . _build/man
Running Sphinx v1.8.5
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
writing... thinkpad-dock.1 { } thinkpad-mutemic.1 { } thinkpad-rotate.1 { } thinkpad-touch.1 { } thinkpad-touchpad.1 { } 
build succeeded.

The manual pages are in _build/man.
gzip -f _build/man/*.1
make[1]: Leaving directory '/home/manderso/git/thinkpad-scripts/doc'
manderso@thinky:~/git/thinkpad-scripts$ sudo make instlal
[sudo] password for manderso: 
manderso@thinky:~/git/thinkpad-scripts$ sudo make install
[sudo] password for manderso: 
install -d "/lib/udev/rules.d/"
install -m 644 81-thinkpad-dock.rules -t "/lib/udev/rules.d/"
install -d "/lib/udev/hwdb.d/"
install -m 644 90-X2x0T-keyboard.hwdb -t "/lib/udev/hwdb.d/"
install -d "/etc/acpi/events/"
install -m 644 thinkpad-mutemic-acpi-hook -t "/etc/acpi/events/"
install -m 644 thinkpad-rotate-acpi-hook-1-normal -t "/etc/acpi/events/"
install -m 644 thinkpad-rotate-acpi-hook-1-rotated -t "/etc/acpi/events/"
install -m 644 thinkpad-rotate-acpi-hook-2-normal -t "/etc/acpi/events/"
install -m 644 thinkpad-rotate-acpi-hook-2-rotated -t "/etc/acpi/events/"
install -m 644 thinkpad-dock-acpi-hook-1-on -t "/etc/acpi/events/"
install -m 644 thinkpad-dock-acpi-hook-1-off -t "/etc/acpi/events/"
install -m 644 thinkpad-dock-acpi-hook-2 -t "/etc/acpi/events/"
cd desktop && make install
make[1]: Entering directory '/home/manderso/git/thinkpad-scripts/desktop'
install -d "/usr/share/applications/"
for desktopfile in thinkpad-dock-off.desktop thinkpad-rotate-left.desktop thinkpad-touch.desktop thinkpad-dock-on.desktop thinkpad-rotate-flip.desktop thinkpad-touchpad.desktop thinkpad-rotate.desktop; do \
	install -m 644 "$desktopfile" -t "/usr/share/applications/"; \
	done
make[1]: Leaving directory '/home/manderso/git/thinkpad-scripts/desktop'
cd doc && make install
make[1]: Entering directory '/home/manderso/git/thinkpad-scripts/doc'
if ls _build/man/*.1.gz &> /dev/null; then \
    install -d "/usr/share/man/man1/"; \
    install -m 644 _build/man/*.1.gz -t "/usr/share/man/man1/"; \
fi
make[1]: Leaving directory '/home/manderso/git/thinkpad-scripts/doc'

======== One more Step! ==================

You might have to call `./setup.py install` to install the actual scripts after this and restart the services. Please consult the “Getting Started” guide which can be found at `doc/guides/getting-started.rst` or on the web at:

http://thinkpad-scripts.readthedocs.org/en/latest/guides/getting-started.html#build-manually

==========================================

manderso@thinky:~/git/thinkpad-scripts$ sudo ./setup.py install
This is running on:
3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008]

running install
running bdist_egg
running egg_info
writing thinkpad_scripts.egg-info/PKG-INFO
writing dependency_links to thinkpad_scripts.egg-info/dependency_links.txt
writing entry points to thinkpad_scripts.egg-info/entry_points.txt
writing top-level names to thinkpad_scripts.egg-info/top_level.txt
reading manifest file 'thinkpad_scripts.egg-info/SOURCES.txt'
writing manifest file 'thinkpad_scripts.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/tps
copying build/lib/tps/main_touchscreen.py -> build/bdist.linux-x86_64/egg/tps
copying build/lib/tps/input.py -> build/bdist.linux-x86_64/egg/tps
copying build/lib/tps/main_touchpad.py -> build/bdist.linux-x86_64/egg/tps
copying build/lib/tps/main_trackpoint.py -> build/bdist.linux-x86_64/egg/tps
copying build/lib/tps/config.py -> build/bdist.linux-x86_64/egg/tps
copying build/lib/tps/__init__.py -> build/bdist.linux-x86_64/egg/tps
copying build/lib/tps/vkeyboard.py -> build/bdist.linux-x86_64/egg/tps
copying build/lib/tps/dock.py -> build/bdist.linux-x86_64/egg/tps
copying build/lib/tps/sound.py -> build/bdist.linux-x86_64/egg/tps
copying build/lib/tps/rotate.py -> build/bdist.linux-x86_64/egg/tps
copying build/lib/tps/unity.py -> build/bdist.linux-x86_64/egg/tps
copying build/lib/tps/screen.py -> build/bdist.linux-x86_64/egg/tps
copying build/lib/tps/default.ini -> build/bdist.linux-x86_64/egg/tps
copying build/lib/tps/network.py -> build/bdist.linux-x86_64/egg/tps
creating build/bdist.linux-x86_64/egg/tps/testsuite
copying build/lib/tps/testsuite/test_input.py -> build/bdist.linux-x86_64/egg/tps/testsuite
copying build/lib/tps/testsuite/test_screen.py -> build/bdist.linux-x86_64/egg/tps/testsuite
copying build/lib/tps/testsuite/__init__.py -> build/bdist.linux-x86_64/egg/tps/testsuite
copying build/lib/tps/testsuite/test_dock.py -> build/bdist.linux-x86_64/egg/tps/testsuite
copying build/lib/tps/testsuite/test_network.py -> build/bdist.linux-x86_64/egg/tps/testsuite
copying build/lib/tps/testsuite/test_hooks.py -> build/bdist.linux-x86_64/egg/tps/testsuite
copying build/lib/tps/testsuite/test_config.py -> build/bdist.linux-x86_64/egg/tps/testsuite
copying build/lib/tps/hooks.py -> build/bdist.linux-x86_64/egg/tps
byte-compiling build/bdist.linux-x86_64/egg/tps/main_touchscreen.py to main_touchscreen.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/tps/input.py to input.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/tps/main_touchpad.py to main_touchpad.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/tps/main_trackpoint.py to main_trackpoint.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/tps/config.py to config.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/tps/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/tps/vkeyboard.py to vkeyboard.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/tps/dock.py to dock.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/tps/sound.py to sound.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/tps/rotate.py to rotate.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/tps/unity.py to unity.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/tps/screen.py to screen.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/tps/network.py to network.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/tps/testsuite/test_input.py to test_input.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/tps/testsuite/test_screen.py to test_screen.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/tps/testsuite/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/tps/testsuite/test_dock.py to test_dock.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/tps/testsuite/test_network.py to test_network.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/tps/testsuite/test_hooks.py to test_hooks.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/tps/testsuite/test_config.py to test_config.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/tps/hooks.py to hooks.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying thinkpad_scripts.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying thinkpad_scripts.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying thinkpad_scripts.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying thinkpad_scripts.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying thinkpad_scripts.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/thinkpad_scripts-4.12.0-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing thinkpad_scripts-4.12.0-py3.7.egg
Removing /usr/local/lib/python3.7/dist-packages/thinkpad_scripts-4.12.0-py3.7.egg
Copying thinkpad_scripts-4.12.0-py3.7.egg to /usr/local/lib/python3.7/dist-packages
thinkpad-scripts 4.12.0 is already the active version in easy-install.pth
Installing thinkpad-config script to /usr/local/bin
Installing thinkpad-dock script to /usr/local/bin
Installing thinkpad-dock-hook script to /usr/local/bin
Installing thinkpad-mutemic script to /usr/local/bin
Installing thinkpad-rotate script to /usr/local/bin
Installing thinkpad-rotate-hook script to /usr/local/bin
Installing thinkpad-scripts-config-migration script to /usr/local/bin
Installing thinkpad-touch script to /usr/local/bin
Installing thinkpad-touchpad script to /usr/local/bin
Installing thinkpad-trackpoint script to /usr/local/bin

Installed /usr/local/lib/python3.7/dist-packages/thinkpad_scripts-4.12.0-py3.7.egg
Processing dependencies for thinkpad-scripts==4.12.0
Finished processing dependencies for thinkpad-scripts==4.12.0

manderso@thinky:~/git/thinkpad-scripts$ sudo systemctl restart acpid
```
I appreciate your help and patience with this.

**Comment by martin-ueding** [comment]
The installation looks good, please show me the output of `thinkpad-rotate -vv`.

**Comment by martin-ueding** [comment]
Okay, and that properly rotates the screen? The issue is that physically rotating the screen does not trigger the rotation? Can you run `acpi_listen` in a shell, rotate and fold the screen and open and rotate back again?

**Comment by manderso7** [comment]
Yes, it does rotate the screen. When I physically rotate the screen and
rotate it back, after running acpi_listen, the output is this:
manderso@thinky:~/git/lollypop$ acpi_listen
video/tabletmode TBLT 0000008A 00000001
video/tabletmode TBLT 0000008A 00000000
^C

**Comment by martin-ueding** [comment]
So the rotation manually works, the ACPI events come up. But the rotation is not automatically triggered when you do the physical rotation?

In that case it could be a permissions issue. Can you please take a look into the syslog (`journalctl`) and see if a call for `su` or `sudo` has been denied around the time that you have physically rotated the screen (sometimes the keyword `AVC` is listed there as well)?

**Comment by manderso7** [comment]
`manderso@thinky:~$ journalctl -f
-- Logs begin at Tue 2019-12-24 13:30:43 EST. --
Jan 08 08:05:24 thinky dbus-daemon[926]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service' requested by ':1.13' (uid=0 pid=927 comm="/usr/sbin/NetworkManager --no-daemon " label="unconfined")
Jan 08 08:05:24 thinky systemd[1]: Starting Network Manager Script Dispatcher Service...
Jan 08 08:05:24 thinky dbus-daemon[926]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Jan 08 08:05:24 thinky systemd[1]: Started Network Manager Script Dispatcher Service.
Jan 08 08:05:24 thinky systemd-resolved[713]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
Jan 08 08:05:32 thinky xdg-desktop-por[2103]: Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: App introspection not allowed
Jan 08 08:05:34 thinky systemd[1]: NetworkManager-dispatcher.service: Succeeded.
Jan 08 08:05:34 thinky systemd-resolved[713]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
Jan 08 08:05:34 thinky systemd-resolved[713]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
Jan 08 08:06:32 thinky xdg-desktop-por[2103]: Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: App introspection not allowed
`
I don't see anything here unfortunately. This is after I rotate, and then rotate it back.

**Comment by martin-ueding** [comment]
I don't have an Ubuntu system at hand, and I know that it uses AppArmor and not SELinux. Perhaps you have something like `/var/log/audit` which might have additional logs regarding security issues? Perhaps you are able to find something of relevance there.

**Comment by Troy-Hendry** [comment]
same problem here; for me it installed the scripts in /usr/local/bin
I created setup.cfg with the following contents:

[install_scripts]
install_dir = /usr/bin

and re-ran setup.py install_scripts

hope that helps, thanks for all the work!

**Comment by manderso7** [comment]
after running aa-status, I see that there's not an apparmor profile dedicated to thinkpad* binaries. 
The only thing I see in journalctl when I rotate the screen is:
Jan 15 08:11:48 thinky xdg-desktop-por[4333]: Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: App introspection not allowed

Thought this may be a red herring.

**Comment by martin-ueding** [comment]
@Troy-Hendry: Perhaps one should modernize the Python installation and replace the `setup.py` with a `setup.cfg` at some point. But the scripts should be installed into `/usr/local/bin` with either method. So your approach put them into `/usr/bin`? That's not recommended as this is the domain of the package manager. Rather add `/usr/local/bin` to your `PATH` environment variable.

@manderso7: I have no idea then. It seems that the parts are in place but something is not working, but we don't have a log file.

**Comment by Troy-Hendry** [comment]
@martin-ueding agreed, usr/bin is a hack -- to confirm, it did placed the scripts there, and (at last screen rotation) works there. But the acpi hooks are hard-coded for it, and I suspect that's the place to make the "proper" change. Happy to do a bit of legwork, let me know.

**Comment by martin-ueding** [comment]
Ah! Now I get the connection. Okay, the ACPI hooks expect an installation with the package and not manually. That should be easy to fix.

**Comment by martin-ueding** [comment]
I have updated the paths, please install the `master` version again.

**Comment by Troy-Hendry** [comment]
typo, local/bin, bin/local

**Comment by martin-ueding** [comment]
@Troy-Hendry: What do you mean? `/usr/bin/local` makes no sense.

**Comment by Troy-Hendry** [comment]
@martin-ueding : Thanks for bearing with me, I was brief because you were so responsive, I appreciate it. In order to clarify I just filed #151  

thanks again, and enjoy your day

**Comment by martin-ueding** [comment]
Sorry for not getting what you meant, I just did the change without too much care apparently. Thanks for pointing it out!
