### ISSUE TITLE
Auto rotate does not work and acpi_listen reports nothing on physical rotation (X220T)

### ISSUE THREAD

**Issue by mruiz42** [martin-ueding/thinkpad-scripts#150]
I am not sure why, but I cannot get the hardware signal during rotation to work. I recently reinstalled arch linux and this time I cannot have the screen rotate, even though it did it automatically before. I forgot what I did to set it up when I installed arch a few months ago. Is there something I am missing that would cause acpi_listen to not report any change in screen position?

**Comment by martin-ueding** [comment]
Did you try `acpi_listen` as root? From the [manual that we have on that](https://thinkpad-scripts.readthedocs.io/en/latest/guides/acpi_listen.html) it seems that ACPI should report that. It could be that some other hardware event daemon now does this.

I have just tried this on my Fedora 31 with my X220 Tablet and it gives the expected output:

```
# acpi_listen 
video/tabletmode TBLT 0000008A 00000001
video/tabletmode TBLT 0000008A 00000000
```

So I have no idea idea what you are missing there.

**Comment by mruiz42** [comment]
I'm very sorry... I had rotated the screen looking for the signal without setting the screen down against the keyboard, which will initiate the acpi_signal.... all is running fine... this is very embarrassing for me, but at least it is solved. I just had to set the screen down for it to work.

**Comment by martin-ueding** [comment]
Happy to hear that it works now!
