### ISSUE TITLE
Thinkpad-rotate not functioning since 4.11.0-1

### ISSUE THREAD

**Issue by emil-backstrand** [martin-ueding/thinkpad-scripts#154]
Hello, I am getting this error when trying to rotate the display on an X230T. It has been working fine before updating.

> Traceback (most recent call last):
>   File "/usr/bin/thinkpad-rotate", line 6, in <module>
>     from pkg_resources import load_entry_point
>   File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3240, in <module>
>     def _initialize_master_working_set():
>   File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3223, in _call_aside
>     f(*args, **kwargs)
>   File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3252, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 568, in _build_master
>     ws.require(__requires__)
>   File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 885, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 771, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'thinkpad-scripts==4.11.0' distribution was not found and is required by the application

**Comment by martin-ueding** [comment]
Could you please post the output of `python3 --version` and `/usr/bin/python3 -c 'import sys; print(sys.path)'`?

Did you install it via an Ubuntu package or from source? I have a hunch that the files went into `/usr/local/lib` and not `/usr/lib`.

**Comment by Emulle** [comment]
Thanks for getting back to me so quickly.  
  
Here is the requested output:  
**Python3 --version**
> Python 3.9.1  
  
**/usr/bin/python3 -c 'import sys; print(sys.path)'**  
> ['', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/home/emulle/.local/lib/python3.9/site-packages', '/usr/lib/python3.9/site-packages']  
  
I am using Arch Linux and have installed the package from the AUR.

**Comment by martin-ueding** [comment]
Could you check whether the there is a `thinkpad-scripts` directory in `/usr/local/lib/python3.9/site-packages`? If that is the case, we have the paths mixed up.

**Comment by jturner314** [comment]
Rebuilding the AUR package will probably fix the issue. At least on Arch, there's a new directory for every minor release of Python (3.7, 3.8, 3.9, etc.). I've noticed that packages that use Python have to be rebuilt for every minor release of Python. I suppose I should bump the version of the AUR package so that users who're using an automated AUR helper will automatically rebuild the package.

**Comment by Emulle** [comment]
> Could you check whether the there is a `thinkpad-scripts` directory in `/usr/local/lib/python3.9/site-packages`? If that is the case, we have the paths mixed up.

There was no thinkpad-scripts directory in '/usr/local/lib/python3.9/site-packages'. In fact there is no directory in '/usr/local/lib/' at all. 

> Will you please confirm whether or not rebuilding the package fixes the issue? (If it does, I'll bump the `pkgrel` of the AUR package.)

This fixes the issue, thanks!

**Comment by jturner314** [comment]
Thanks for confirming. It looks like I need to update the version anyway. (The AUR package is currently 4.11.0, while the latest release is 4.12.0.) I don't use my X220 tablet anymore, so I haven't been keeping up with this project as closely.

**Comment by Emulle** [comment]
> Thanks for confirming. It looks like I need to update the version anyway. (The AUR package is currently 4.11.0, while the latest release is 4.12.0.) I don't use my X220 tablet anymore, so I haven't been keeping up with this project as closely.
> 
> I've updated the AUR package to 4.12.0.

Cheers, Thanks to both you and Martin for still keeping your eyes on this project. Been using my X230 as an e-book/pdf reader for my course literature, and this script makes it much easier to use it in that manner.
