### ISSUE TITLE
thinkpad-touch behavior after resume from suspend 

### ISSUE THREAD

**Issue by vertighel** [martin-ueding/thinkpad-scripts#70]
On resume from suspension, the `thinkpad-touch on|off` command does not have any effect. 

In particular, if the touchscreen is disabled, before suspension,  it is not possible to re-enable the touchscreen on resume.

If it is suspended/resumed again, than the script starts again working.

**Comment by martin-ueding** [comment]
I have not got any feedback for almost a year now, I close this one.
