### ISSUE TITLE
Restart avahi-daemon

### ISSUE THREAD

**Issue by martin-ueding** [martin-ueding/thinkpad-scripts#83]
I noticed that the `.local` addresses stop working when I switch the network interface with `thinkpad-dock`. I also have to restart `avahi-daemon`. On Ubuntu 14.04, this works via `service avahi-daemon restart`, but requires superuser privileges. Since `thinkpad-dock` currently is a user program, this would not work directly.

This is not really pressing, I just want to preserve this thought.

**Comment by jturner314** [comment]
One possibility is to use a setuid executable, but I would be hesitant to do this -- unless done carefully, it would be a security risk.

**Comment by martin-ueding** [comment]
Maybe this is something that will improve with systemd, but setuid program is just asking for trouble, I think.

**Comment by martin-ueding** [comment]
Now I am on Fedora, there is no Avahi used by default. Also my FRITZ!Box router has some DNS, so I do not really need that any more.
