### ISSUE TITLE
Out-of-date documentation

### ISSUE THREAD

**Issue by jturner314** [martin-ueding/thinkpad-scripts#90]
The man page for `thinkpad-touch` is out-of-date. (It still discusses using the old-style Bash script configuration instead of the new INI configuration.)

Additionally, there appears to be a `thinkpad-trackpoint` script. Is that intended for the user to use directly? If so, it needs a man page too.

I can write a pull request for these; I just created this issue so I won't forget.

**Comment by martin-ueding** [comment]
I will look into this after lunch today.

**Comment by martin-ueding** [comment]
It's after dinner by now. I will write manual pages for all the scripts now and check that they all are up to date.
