### ISSUE TITLE
Add support for Thinkpad Yoga

### ISSUE THREAD

**Issue by jturner314** [martin-ueding/thinkpad-scripts#91]
I received an email from a user of the Arch Linux package asking how to setup `thinkpad-touch` to work properly on the Thinkpad Yoga.

Problem
-----------

The xinput devices are:
```
$ xinput --list
⎡ Virtual core pointer                          id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                id=4    [slave pointer  (2)]
⎜   ↳ Wacom ISDv4 EC Pen stylus                 id=11   [slave pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad                id=13   [slave pointer  (2)]
⎜   ↳ Wacom ISDv4 EC Pen eraser                 id=15   [slave pointer  (2)]
⎜   ↳ TPPS/2 IBM TrackPoint                     id=16   [slave pointer  (2)]
⎜   ↳ ELAN Touchscreen                          id=9    [slave pointer  (2)]
⎣ Virtual core keyboard                         id=3    [master keyboard (2)]
    ↳ Virtual core XTEST keyboard               id=5    [slave keyboard (3)]
    ↳ Power Button                              id=6    [slave keyboard (3)]
    ↳ Video Bus                                 id=7    [slave keyboard (3)]
    ↳ Power Button                              id=8    [slave keyboard (3)]
    ↳ Integrated Camera                         id=10   [slave keyboard (3)]
    ↳ AT Translated Set 2 keyboard              id=12   [slave keyboard (3)]
    ↳ ThinkPad Extra Buttons                    id=14   [slave keyboard (3)]
```

The touchscreen is `ELAN Touchscreen`, which causes two problems:

1. `thinkpad-touch` is hardcoded to use the name `Wacom ISDv4 E6 Finger touch` to identify the touchscreen.
2. `xsetwacom` does not seem to work (based on the information provided). (The `ELAN Touchscreen` is probably not using the Wacom drivers.)

Suggestions
----------------

Regarding problem 1, we can make this configurable. While we're at it, we probably should make the other hard-coded strings in the various `main_*()` methods of `input.py` configurable as well.

Regarding problem 2, we can mostly replace `xsetwacom` with `xinput`. On my X220 Tablet, I can do things like call
```
xinput --set-prop <ID> "Device Enabled" 0
```
to disable the touchscreen, and call
```
xinput --set-prop <ID> "Wacom Rotation" <NUMBER>
```
to rotate the screen to an orientation corresponding to `<NUMBER>`. The only option for which this is not straightforward is `MapToOutput`. The `xinput` equivalent is a `Coordinate Transformation Matrix`, which is somewhat difficult to calculate and depends on the geometry of the connected screens. (See [here](http://ubuntuforums.org/showthread.php?t=1656089).) Where possible, though, I think it would be a good idea to replace `xsetwacom` with `xinput` to reduce external dependencies and improve support for non-Wacom devices.

I'm pretty busy this week, so I won't get to work on a pull request until at least this weekend.

Questions for Yoga user
-------------------------------

Can you confirm that
```
xsetwacom --set 9 Touch On
```
does not work and
```
xinput --set-prop 9 "Device Enabled" 1
```
or something similar does work?

What is the output of the following?
```
xinput --list-props 9
```

(You may need to update `9` with the correct id of your touchscreen if it has changed since the initial bug report.)

**Comment by kdex** [comment]
Hi there,

I just tried to disable the touchscreen with
```
0 ✓ kdex@punchy ~ $ xsetwacom --set 9 Touch Off
Property 'Wacom Enable Touch' does not exist on device.
0 ✓ kdex@punchy ~ $ 
```
and although this message looks somewhat wrong, it does indeed disable the touchscreen. I'm still not sure why this works, though.

Re-enabling it like this produces the same behavior:
```
0 ✓ kdex@punchy ~ $ xsetwacom --set 9 Touch On
Property 'Wacom Enable Touch' does not exist on device.
0 ✓ kdex@punchy ~ $ 
```
Once executed, the touchscreen works again.

**If I set the property directly via xinput as you mentioned, no such message is displayed, and I can confirm that disabling and enabling it works flawlessly.**

Lastly, here's some device properties:
```
0 ✓ kdex@punchy ~ $ xinput --list-props 9
Device 'ELAN Touchscreen':
        Device Enabled (138):   1
        Coordinate Transformation Matrix (140): 1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
        Device Accel Profile (270):     0
        Device Accel Constant Deceleration (271):       1.000000
        Device Accel Adaptive Deceleration (272):       1.000000
        Device Accel Velocity Scaling (273):    10.000000
        Device Product ID (257):        1267, 596
        Device Node (258):      "/dev/input/event1"
        Evdev Axis Inversion (274):     0, 0
        Evdev Axis Calibration (275):   <no items>
        Evdev Axes Swap (276):  0
        Axis Labels (277):      "Abs MT Position X" (266), "Abs MT Position Y" (267), "Abs MT Touch Major" (263), "Abs MT Touch Minor" (264), "Abs MT Orientation" (265), "Abs MT Tool X" (268), "Abs MT Tool Y" (269), "None" (0), "None" (0)
        Button Labels (278):    "Button Unknown" (260), "Button Unknown" (260), "Button Unknown" (260), "Button Wheel Up" (144), "Button Wheel Down" (145)
        Evdev Scrolling Distance (279): 0, 0, 0
        Evdev Middle Button Emulation (280):    0
        Evdev Middle Button Timeout (281):      50
        Evdev Third Button Emulation (282):     0
        Evdev Third Button Emulation Timeout (283):     1000
        Evdev Third Button Emulation Button (284):      3
        Evdev Third Button Emulation Threshold (285):   20
        Evdev Wheel Emulation (286):    0
        Evdev Wheel Emulation Axes (287):       0, 0, 4, 5
        Evdev Wheel Emulation Inertia (288):    10
        Evdev Wheel Emulation Timeout (289):    200
        Evdev Wheel Emulation Button (290):     4
        Evdev Drag Lock Buttons (291):  0
0 ✓ kdex@punchy ~ $ 
```

**Comment by martin-ueding** [comment]
Okay, I just moved the strings into the configuration as you can see in the referenced commit above. You could try to adapt the configuration file with the name of your screen. I will update the documentation with new configuration options and then see about using `xinput` instead of `xsetwacom`.

**Comment by martin-ueding** [comment]
Currently (v4.2.1), `thinkpad-touch` will call `xinput set-prop 14 Device Enabled 1` and `xsetwacom --set 14 Touch On` on my X220 Tablet. The touchscreen is toggled without any error messages. Then I tried to remove the `xsetwacom` line and only used `xinput`.

- If the touchscreen was set to off with `xsetwacom`, `xinput` alone could not activate it.
- If the touchscreen was on, `xinput` alone could deactivate and later activate it.

So once you have changed the string in the configuration, it should work for you right away, probably with the warning from `xsetwacom`.

Since one could disable the touchscreen on my machine with `xsetwacom` (or some other tool that uses that), `thinkpad-touch` would not be able to activate the touch screen again without using `xsetwacom`. Therefore, I would like to keep it there as the default. `xinput` was there all along, I forgot about that.

I will put in a configuration option that will let you choose to call `xsetwacom` for toggling the touch screen.

@kdex: Could you please change your configuration and tell us whether it works then?

**Comment by jturner314** [comment]
The reason why `xinput` does not reenable the touchscreen after using `xsetwacom` to disable it is that they are modifying different parameters. The parameters of the X220 tablet touchscreen are:
```shell
$ xinput --list-props 14
Device 'Wacom ISDv4 E6 Finger touch':
	Device Enabled (138):	1
	Coordinate Transformation Matrix (140):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	Device Accel Profile (262):	0
	Device Accel Constant Deceleration (263):	1.000000
	Device Accel Adaptive Deceleration (264):	1.000000
	Device Accel Velocity Scaling (265):	10.000000
	Device Node (258):	"/dev/input/event9"
	Wacom Tablet Area (294):	0, 0, 2776, 1569
	Wacom Rotation (295):	0
	Wacom Pressurecurve (296):	0, 0, 100, 100
	Wacom Serial IDs (297):	230, 1, 3, 0, 0
	Wacom Serial ID binding (298):	0
	Wacom Pressure Threshold (299):	0
	Wacom Sample and Suppress (300):	2, 4
	Wacom Enable Touch (301):	1
	Wacom Enable Touch Gesture (303):	1
	Wacom Touch Gesture Parameters (304):	121, 54, 250
	Wacom Tool Type (305):	"TOUCH" (312)
	Wacom Button Actions (306):	"Wacom button action 0" (307), "Wacom button action 1" (308), "Wacom button action 2" (309)
	Wacom button action 0 (307):	1572865
	Wacom button action 1 (308):	1572866
	Wacom button action 2 (309):	1572867
	Device Product ID (257):	1386, 230
	Wacom Debug Levels (311):	0, 0
```
`xsetwacom --set 14 Touch On` modifies the `Wacom Enable Touch` parameter, while `xinput --set-prop 14 "Device Enabled" 1` modifies the `Device Enabled` parameter. `xinput` can also be used to modify the `Wacom Enable Touch` parameter (`xinput --set-prop 14 "Wacom Enable Touch" 1`).

Probably the best approach is to modify both parameters with `xinput` (always modify `Device Enabled`, and only modify `Wacom Enable Touch` when it is present). `xinput --list-props 14` can be used to determine whether `Wacom Enable Touch` is a parameter or not.

**Comment by martin-ueding** [comment]
Okay, this is what I did this morning, then. `xinput` is used for `Device Enabled` and if there is `Wacom Touch Enable` in the output of `xinput list-props`, `xinput` will again be called for that option. This eliminates the configuration option.

What still remains is the rotation of the screen through `xinput`. I will look into whether I can get this to work as well. Then @kdex should have it working, except for the mapping to a single output, which is not a problem when no other screen is attached.

**Comment by martin-ueding** [comment]
On my machine, the matrix does not change when I rotate the screen with the current version of `thinkpad-rotate`. With a second screen (1920 × 1080) attached, I have the following matrix:

0.415703, 0.000000, 0.584297,
0.000000, 0.711111, 0.000000,
0.000000, 0.000000, 1.000000

Then I detached the external screen and tried again. With normal rotation, I just got:

1.000000, 0.000000, 0.000000,
0.000000, 1.000000, 0.000000,
0.000000, 0.000000, 1.000000

Flipping it also gave me:

1.000000, 0.000000, 0.000000,
0.000000, 1.000000, 0.000000,
0.000000, 0.000000, 1.000000

Same for left and right.

However, when I compute the transformation matrix by hand and change it, the mapping of the touch screen changed as well. I will now write something that computes the needed transformation matrix and sets it using `xinput`.

----

`xrandr` seems to have a `--map-to-output` option, we can try that later for the output mapping.

**Comment by jturner314** [comment]
These resources may be useful:

* Detailed descriptions of manual calculation of the transformation matrix: http://ubuntuforums.org/showthread.php?t=1656089
* Source code for `xsetwacom` (in particular, see `set_output_xrandr()`): http://sourceforge.net/p/linuxwacom/xf86-input-wacom/ci/master/tree/tools/xsetwacom.c

A combination of `Evdev Axis Inversion` and `Evdev Axes Swap` may be equivalent to a rotation, and maybe the `xinput` `--map-to-output` option would be sufficient to translate/scale the mapping. If so, we could avoid calculating the transformation matrix. (This may be one possibility, but if you'd prefer to calculate the transformation matrix, that works too. Calculating the transformation matrix may be a more versatile method anyway.)

**Comment by martin-ueding** [comment]
So I wrote the matices now, and it seems to work on my machine with an external screen attached. Could you please test whether this now works for you as well?

**Comment by martin-ueding** [comment]
I now removed all `xsetwacom` from the codebase, I hope that I did not break anything.

**Comment by kdex** [comment]
I can confirm that `thinkpad-touch` is now fully supported on my Thinkpad Yoga (after creating the configuration file).

However, as for `thinkpad-rotate`, the output now looks completely broken. It's a little hard to create accurate screenshots after the screen is flipped, therefore, have a look at the following:

[Before](https://kdex.de/pub/thinkpad-scripts/before.jpg)
[During](https://kdex.de/pub/thinkpad-scripts/during.jpg)
[After](https://kdex.de/pub/thinkpad-scripts/after.jpg)

Also, `thinkpad-rotate flip` will end up in a black screen. Once there, I can't even change to another TTY to kill X anymore.

**Comment by jturner314** [comment]
@kdex
I suspect this a bug in `xrandr` or `X11`. What happens when you run `xrandr` directly, like this:
```shell
xrandr --output eDP1 --rotate DIRECTION
```
where `DIRECTION` can be `left`, `right`, `normal`, or `inverted`? (If you call `thinkpad-rotate` with `-vv`, you can see the commands that `thinkpad-rotate` is using, and then test the same commands.)

You may be able to get more details of any errors from `/var/log/Xorg.0.log` or your system log (`sudo journalctl -b`).

If it really is a bug in `xrandr` or `X11`, you could try disabling and reenabling the screen when it looks weird:
```shell
xrandr --output eDP1 --off
xrandr --output eDP1 --auto
```

@martin-ueding
Your transformation matrix code works when I have 0 or 1 external displays attached. (`thinkpad-rotate` crashes when 2 external displays are enabled and the internal one is disabled. See [my comment](https://github.com/martin-ueding/thinkpad-scripts/issues/92#issuecomment-71350307) on #92.)

**Comment by martin-ueding** [comment]
What is the point of using `thinkpad-rotate` when the internal screen is not used? I do not get it, to be honest.

**Comment by jturner314** [comment]
> What is the point of using `thinkpad-rotate` when the internal screen is not used?

There is no point. It would be a little nicer to exit cleanly without an unhandled exception, but it doesn't really matter. I was just providing a complete description of my testing.

**Comment by martin-ueding** [comment]
Okay, so what is the state of *this* bug? The transformation seems to work, except that the screen of @kdex has glitches after rotating. Is this something that we could possible do here, or should I close this issue now?

**Comment by kdex** [comment]
When I just tried again, I could not reproduce the glitches. There might have been several `pacman` updates and reboots between my last comment and now, so I might be using a newer `xorg` version by now. Rotating does indeed appear to work on my Thinkpad Yoga now.

I have also verified that the touchscreen coordinates are mapped correctly after rotating. The only thing I want to leave here is the following output of two rotation procedures that appear to cause an exception in your code:

```javascript
0 ✓ kdex@punchy ~ $ thinkpad-rotate left  
  1.000000  0.000000  0.000000
  0.000000  1.000000  0.000000                                                        
  0.000000  0.000000  1.000000                                                        
                                                                                      
  0.000000 -1.000000  1.000000                                                        
  1.000000  0.000000  0.000000                                                        
  0.000000  0.000000  1.000000                                                        
No such schema 'org.gnome.settings-daemon.plugins.xsettings'                          
tps.screen    ERROR    Command '['gsettings', 'set', 'org.gnome.settings-daemon.plugins.xsettings', 'rgba-order', 'vrgb']' returned non-zero exit status 1                  
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.                                                                       
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.                                                                       
0 ✓ kdex@punchy ~ $ thinkpad-rotate normal                                            
  1.000000  0.000000  0.000000                                                        
  0.000000  1.000000  0.000000
  0.000000  0.000000  1.000000

  1.000000  0.000000  0.000000
  0.000000  1.000000  0.000000
  0.000000  0.000000  1.000000
No such schema 'org.gnome.settings-daemon.plugins.xsettings'
tps.screen    ERROR    Command '['gsettings', 'set', 'org.gnome.settings-daemon.plugins.xsettings', 'rgba-order', 'rgb']' returned non-zero exit status 1
0 ✓ kdex@punchy ~ $ 
```
I'm not quite sure about what this is, but I would like to note that this might be caused due to the fact that I do not use GNOME, but KDE Plasma 5 (but that's just a wild guess). You might want to add an additional check for that.

Other than that, the main goal of this ticket has been reached: Thinkpad Yogas seem to be fully supported now, so as soon as these (GNOME-related?) hiccups are resolved, this ticket can be closed.

**Comment by jturner314** [comment]
> I'm not quite sure about what this is, but I would like to note that this might be caused due to the fact that I do not use GNOME, but KDE Plasma 5 (but that's just a wild guess). You might want to add an additional check for that.

This is related to changing the subpixel anti-aliasing orientation of the display. The code checks if `xfconf-query` (for XFCE) or `gsettings` (for GNOME) is installed and uses the appropriate command to perform the subpixel rotation. If neither is installed, it warns the user but does nothing.

You're seeing an error message instead of warning message because you have `gsettings` installed even though you're using KDE. I think the default behavior is reasonable because most KDE users don't have `gsettings` installed. Regardless, nothing bad is happening, you'll just see these messages in your logs.

I suppose we could use `gsettings` to check if the `org.gnome.settings-daemon.plugins.xsettings` schema exists before trying to set the variable, but I don't think it's worth the effort.

By the way, I'm a little suprised that the touchscreen rotates. I would think this configuration setting would be necessary in `~/.config/thinkpad-scripts/config.ini`:
```
[touch]
regex = (Wacom ISD|ELAN Touchscreen).*id=(\d+)
```
@kdex If you get a chance, will you please post the output of `thinkpad-rotate -vv left` with and without this setting?
@martin-ueding Am I missing something here? Why does it work without this setting? (My guess is that the desktop environment handles it, because I wouldn't think `thinkpad-rotate` would rotate the touchscreen without this.)

**Comment by kdex** [comment]
When I rotated the screen, I noticed that using the stylus, the coordinates were mapped correctly, but using my finger, they were not.

Then I turned on the setting that you @jturner314 mentioned, and what happened was that both input methods (both my finger and the stylus) were mapped wrong (but both appeared to be pointing to the same wrong coordinates).

Here's a little bit of output:

Without the setting:
```javascript
0 ✓ kdex@punchy ~ $ thinkpad-rotate -vv left
tps.config    DEBUG    ----------------------------------
tps.config    DEBUG    Program was started with arguments: ['/usr/bin/thinkpad-rotate', '-vv', 'left']
tps.config    DEBUG    Default configfile is /home/kdex/.python-eggs/thinkpad_scripts-4.2.1-py3.4.egg-tmp/tps/default.ini.
tps.screen    DEBUG    subprocess “xrandr -q --verbose”
tps           DEBUG    Converted “normal” to “Direction(xrandr='normal', subpixel='rgb', physically_closed=False, rot_mat=[1, 0, 0, 0, 1, 0, 0, 0, 1])”.
tps.screen    INFO     Current rotation is “Direction(xrandr='normal', subpixel='rgb', physically_closed=False, rot_mat=[1, 0, 0, 0, 1, 0, 0, 0, 1])”.
tps           DEBUG    Converted “left” to “Direction(xrandr='left', subpixel='vrgb', physically_closed=True, rot_mat=[0, -1, 1, 1, 0, 0, 0, 0, 1])”.
tps.rotate    INFO     User chose to set to Direction(xrandr='left', subpixel='vrgb', physically_closed=True, rot_mat=[0, -1, 1, 1, 0, 0, 0, 0, 1])
tps           DEBUG    Command “/home/kdex/.config/thinkpad-scripts/hooks/prerotate” not found.
tps.screen    DEBUG    subprocess “xrandr --output eDP1 --rotate left”
tps.screen    DEBUG    subprocess “xrandr -q”
  1.000000  0.000000  0.000000
  0.000000  1.000000  0.000000
  0.000000  0.000000  1.000000

  0.000000 -1.000000  1.000000
  1.000000  0.000000  0.000000
  0.000000  0.000000  1.000000
tps.config    DEBUG    Default configfile is /home/kdex/.python-eggs/thinkpad_scripts-4.2.1-py3.4.egg-tmp/tps/default.ini.
tps.input     DEBUG    Using “Wacom ISD.*id=(\d+)” as regex to find Wacom devices.    
tps.input     DEBUG    subprocess “xinput”                                            
tps.input     DEBUG    subprocess “xinput set-prop 11 Coordinate Transformation Matrix 0.0 -1.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0”                                                
tps.screen    DEBUG    subprocess “xrandr”                                            
tps           DEBUG    Command “xfconf-query” not found.                              
tps           DEBUG    Command “gsettings” found.                                     
tps.screen    DEBUG    subprocess “gsettings set org.gnome.settings-daemon.plugins.xsettings rgba-order vrgb”                                                               
No such schema 'org.gnome.settings-daemon.plugins.xsettings'                          
tps.screen    ERROR    Command '['gsettings', 'set', 'org.gnome.settings-daemon.plugins.xsettings', 'rgba-order', 'vrgb']' returned non-zero exit status 1                  
tps.vkeyboard DEBUG    subprocess “pgrep kvkbd”                                       
tps           DEBUG    Command “kvkbd” found.                                         
tps.vkeyboard DEBUG    kvkbd                                                          
tps.input     DEBUG    subprocess “xinput list”                                       
tps.input     DEBUG    subprocess “xinput set-prop 15 Device Enabled 0”               
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.                                                                       
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
tps.input     DEBUG    subprocess “xinput list”
tps.input     DEBUG    subprocess “xinput set-prop 13 Device Enabled 0”
tps           DEBUG    Command “/home/kdex/.config/thinkpad-scripts/hooks/postrotate” not found.
0 ✓ kdex@punchy ~ $
```

And with the above setting:
```javascript
0 ✓ kdex@punchy ~ $ thinkpad-rotate -vv left                  
tps.config    DEBUG    ----------------------------------
tps.config    DEBUG    Program was started with arguments: ['/usr/bin/thinkpad-rotate', '-vv', 'left']
tps.config    DEBUG    Default configfile is /home/kdex/.python-eggs/thinkpad_scripts-4.2.1-py3.4.egg-tmp/tps/default.ini.
tps.screen    DEBUG    subprocess “xrandr -q --verbose”
tps           DEBUG    Converted “normal” to “Direction(xrandr='normal', subpixel='rgb', physically_closed=False, rot_mat=[1, 0, 0, 0, 1, 0, 0, 0, 1])”.
tps.screen    INFO     Current rotation is “Direction(xrandr='normal', subpixel='rgb', physically_closed=False, rot_mat=[1, 0, 0, 0, 1, 0, 0, 0, 1])”.
tps           DEBUG    Converted “left” to “Direction(xrandr='left', subpixel='vrgb', physically_closed=True, rot_mat=[0, -1, 1, 1, 0, 0, 0, 0, 1])”.
tps.rotate    INFO     User chose to set to Direction(xrandr='left', subpixel='vrgb', physically_closed=True, rot_mat=[0, -1, 1, 1, 0, 0, 0, 0, 1])
tps           DEBUG    Command “/home/kdex/.config/thinkpad-scripts/hooks/prerotate” not found.
tps.screen    DEBUG    subprocess “xrandr --output eDP1 --rotate left”
tps.screen    DEBUG    subprocess “xrandr -q”
  1.000000  0.000000  0.000000
  0.000000  1.000000  0.000000
  0.000000  0.000000  1.000000                                                        
                                                                                      
  0.000000 -1.000000  1.000000                                                        
  1.000000  0.000000  0.000000                                                        
  0.000000  0.000000  1.000000                                                        
tps.config    DEBUG    Default configfile is /home/kdex/.python-eggs/thinkpad_scripts-4.2.1-py3.4.egg-tmp/tps/default.ini.                                                  
tps.input     DEBUG    Using “(Wacom ISD|ELAN Touchscreen).*id=(\d+)” as regex to find Wacom devices.                                                                       
tps.input     DEBUG    subprocess “xinput”                                            
Traceback (most recent call last):                                                    
  File "/usr/bin/thinkpad-rotate", line 9, in <module>                                
    load_entry_point('thinkpad-scripts==4.2.1', 'console_scripts', 'thinkpad-rotate')()                                                                                     
  File "/usr/lib/python3.4/site-packages/thinkpad_scripts-4.2.1-py3.4.egg/tps/rotate.py", line 37, in main                                                                  
  File "/usr/lib/python3.4/site-packages/thinkpad_scripts-4.2.1-py3.4.egg/tps/rotate.py", line 46, in rotate_to                                                             
  File "/usr/lib/python3.4/site-packages/thinkpad_scripts-4.2.1-py3.4.egg/tps/input.py", line 74, in map_rotate_all_input_devices                                           
  File "/usr/lib/python3.4/site-packages/thinkpad_scripts-4.2.1-py3.4.egg/tps/input.py", line 51, in get_wacom_device_ids
ValueError: invalid literal for int() with base 10: b'ELAN Touchscreen'
1 ✗ kdex@punchy ~ $            
```

**Comment by jturner314** [comment]
@kdex Sorry, it looks like I gave you a broken regex. This should work properly:
```
[touch]
regex = (?:Wacom ISD|ELAN Touchscreen).*id=(\d+)
```
(The earlier regex captured the first set of parentheses in addition to the id number; this makes the first set of parentheses non-capturing.)

**Comment by kdex** [comment]
@jturner314 I see. Here's one more try with the fixed regex:

```javascript
0 ✓ kdex@punchy ~ $ thinkpad-rotate -vv left                  
tps.config    DEBUG    ----------------------------------
tps.config    DEBUG    Program was started with arguments: ['/usr/bin/thinkpad-rotate', '-vv', 'left']
tps.config    DEBUG    Default configfile is /home/kdex/.python-eggs/thinkpad_scripts-4.2.1-py3.4.egg-tmp/tps/default.ini.
tps.screen    DEBUG    subprocess “xrandr -q --verbose”
tps           DEBUG    Converted “normal” to “Direction(xrandr='normal', subpixel='rgb', physically_closed=False, rot_mat=[1, 0, 0, 0, 1, 0, 0, 0, 1])”.
tps.screen    INFO     Current rotation is “Direction(xrandr='normal', subpixel='rgb', physically_closed=False, rot_mat=[1, 0, 0, 0, 1, 0, 0, 0, 1])”.
tps           DEBUG    Converted “left” to “Direction(xrandr='left', subpixel='vrgb', physically_closed=True, rot_mat=[0, -1, 1, 1, 0, 0, 0, 0, 1])”.
tps.rotate    INFO     User chose to set to Direction(xrandr='left', subpixel='vrgb', physically_closed=True, rot_mat=[0, -1, 1, 1, 0, 0, 0, 0, 1])
tps           DEBUG    Command “/home/kdex/.config/thinkpad-scripts/hooks/prerotate” not found.
tps.screen    DEBUG    subprocess “xrandr --output eDP1 --rotate left”
tps.screen    DEBUG    subprocess “xrandr -q”
  1.000000  0.000000  0.000000
  0.000000  1.000000  0.000000
  0.000000  0.000000  1.000000

  0.000000 -1.000000  1.000000
  1.000000  0.000000  0.000000                                                        
  0.000000  0.000000  1.000000                                                        
tps.config    DEBUG    Default configfile is /home/kdex/.python-eggs/thinkpad_scripts-4.2.1-py3.4.egg-tmp/tps/default.ini.                                                  
tps.input     DEBUG    Using “(?:Wacom ISD|ELAN Touchscreen).*id=(\d+)” as regex to find Wacom devices.                                                                     
tps.input     DEBUG    subprocess “xinput”                                            
tps.input     DEBUG    subprocess “xinput set-prop 9 Coordinate Transformation Matrix 0.0 -1.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0”                                                 
tps.input     DEBUG    subprocess “xinput set-prop 11 Coordinate Transformation Matrix 0.0 -1.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0”                                                
tps.screen    DEBUG    subprocess “xrandr”                                            
tps           DEBUG    Command “xfconf-query” not found.                              
tps           DEBUG    Command “gsettings” found.                                     
tps.screen    DEBUG    subprocess “gsettings set org.gnome.settings-daemon.plugins.xsettings rgba-order vrgb”                                                               
No such schema 'org.gnome.settings-daemon.plugins.xsettings'                          
tps.screen    ERROR    Command '['gsettings', 'set', 'org.gnome.settings-daemon.plugins.xsettings', 'rgba-order', 'vrgb']' returned non-zero exit status 1                  
tps.vkeyboard DEBUG    subprocess “pgrep kvkbd”                                       
tps           DEBUG    Command “kvkbd” found.
tps.vkeyboard DEBUG    kvkbd
tps.input     DEBUG    subprocess “xinput list”
tps.input     DEBUG    subprocess “xinput set-prop 15 Device Enabled 0”
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
tps.input     DEBUG    subprocess “xinput list”
tps.input     DEBUG    subprocess “xinput set-prop 13 Device Enabled 0”
tps           DEBUG    Command “/home/kdex/.config/thinkpad-scripts/hooks/postrotate” not found.
0 ✓ kdex@punchy ~ $
```

The touchscreen now maps the coordinates as intended, regardless of touching it with a stylus or not.

One more thing about `gsettings` on KDE: This appears to be a default (Core) package on Arch, as there's lots of dependencies (even `systemd` requires it):

```javascript
0 ✓ kdex@punchy ~ $ pacman -Qo /usr/bin/gsettings
/usr/bin/gsettings is owned by glib2 2.42.1-1
0 ✓ kdex@punchy ~ $ remove glib2                 
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: at-spi2-core: requires glib2
:: atk: requires glib2
:: avahi: requires glib2
:: bluez: requires glib2
:: cairo: requires glib2
:: dbus-glib: requires glib2
:: dconf: requires glib2
:: desktop-file-utils: requires glib2
:: fribidi: requires glib2
:: gamin: requires glib2
:: gdk-pixbuf2: requires glib2
:: gettext: requires glib2
:: glib-networking: requires glib2
:: glibmm: requires glib2
:: gobject-introspection: requires glib2
:: gsettings-desktop-schemas: requires glib2
:: gstreamer: requires glib2
:: gstreamer0.10: requires glib2
:: harfbuzz: requires glib2
:: json-glib: requires glib2
:: lib32-glib2: requires glib2
:: libcacard: requires glib2
:: libcroco: requires glib2
:: libdbusmenu-glib: requires glib2
:: libgdiplus: requires glib2
:: libmbim: requires glib2
:: libmm-glib: requires glib2
:: libnice: requires glib2
:: libosinfo: requires glib2
:: libplist: requires glib2
:: libqalculate: requires glib2
:: libqmi: requires glib2
:: libsoup: requires glib2
:: libsystemd: requires glib2
:: libuser: requires glib2
:: pkg-config: requires glib2
:: polkit: requires glib2
:: python2-gobject2: requires glib2
:: rest: requires glib2
:: shared-mime-info: requires glib2
:: speech-dispatcher: requires glib2
:: systemd: requires glib2
:: udisks2: requires glib2
:: vala: requires glib2
:: wireshark-cli: requires glib2
:: wmctrl: requires glib2
1 ✗ kdex@punchy ~ $
```

**Comment by jturner314** [comment]
> The touchscreen now maps the coordinates as intended, regardless of touching it with a stylus or not.

That's great. #96 will add this to the documentation.

> One more thing about `gsettings` on KDE: This appears to be a default (Core) package on Arch, as there's lots of dependencies (even `systemd` requires it):

I didn't realize that. #97 makes it so that if `gsettings` is installed but the `org.gnome.settings-daemon.plugins.xsettings` schema is not present, the log message will be a warning instead of an error. By the way, I just remembered that there's a configuration parameter for this. You can use the following to disable subpixel rotation:
```
[rotate]
subpixels = false
```
I think everything is resolved for this issue, so I'm closing it. If there's anything else, please feel free to comment below.
