### ISSUE TITLE
thinkpad-rotate cannot determine orientation on ThinkPad Yoga

### ISSUE THREAD

**Issue by martin-ueding** [martin-ueding/thinkpad-scripts#92]
I was contacted by @kdex because `thinkpad-rotate` fails on his ThinkPad Yoga with the following traceback:

```console
$ thinkpad-rotate
Traceback (most recent call last):
  File "/usr/bin/thinkpad-rotate", line 9, in <module>
    load_entry_point('thinkpad-scripts==4.2.1', 'console_scripts', 'thinkpad-rotate')()
  File "/usr/lib/python3.4/site-packages/tps/rotate.py", line 32, in main
    options.direction, config)
  File "/usr/lib/python3.4/site-packages/tps/rotate.py", line 87, in new_rotation
    if not current.physically_closed:
AttributeError: 'NoneType' object has no attribute 'physically_closed' 
```

And this is the `xinput` list that he sent me:

```console
$ xinput --list
⎡ Virtual core pointer                          id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                id=4    [slave pointer  (2)]
⎜   ↳ Wacom ISDv4 EC Pen stylus                 id=11   [slave pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad                id=13   [slave pointer  (2)]
⎜   ↳ Wacom ISDv4 EC Pen eraser                 id=15   [slave pointer  (2)]
⎜   ↳ TPPS/2 IBM TrackPoint                     id=16   [slave pointer  (2)]
⎜   ↳ ELAN Touchscreen                          id=9    [slave pointer  (2)]
⎣ Virtual core keyboard                         id=3    [master keyboard (2)]
    ↳ Virtual core XTEST keyboard               id=5    [slave keyboard (3)]
    ↳ Power Button                              id=6    [slave keyboard (3)]
    ↳ Video Bus                                 id=7    [slave keyboard (3)]
    ↳ Power Button                              id=8    [slave keyboard (3)]
    ↳ Integrated Camera                         id=10   [slave keyboard (3)]
    ↳ AT Translated Set 2 keyboard              id=12   [slave keyboard (3)]
    ↳ ThinkPad Extra Buttons                    id=14   [slave keyboard (3)] 
```

----

Now I think that the problem here arises because our program cannot determine the current state which will give a `None` as `current`. I'll have to look into why this is the case on that machine.

**Comment by martin-ueding** [comment]
I looked at the origin of the `None` and there is a possible code path in `tps.screen.get_rotation` which has no explicit `return`, such that a `None` is returned. In that case, I log an error. Could you please give the output of `xrandr` which lists all the screen connected to your machine? I have the hunch that it is not called `LVDS1` as the configuration assumes with the default value in `screen.internal`. If that is the case, then you can change this value in your configuration and it should work. (The error message is supposed to convey this as well.)

**Comment by kdex** [comment]
Sure, here it is:

``
0 ✓ kdex@punchy ~ $ xrandr 
Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 32767 x 32767
eDP1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 276mm x 156mm
   1920x1080     60.04*+
   1400x1050     59.98  
   1280x1024     60.02  
   1280x960      60.00  
   1024x768      60.00  
   800x600       60.32    56.25  
   640x480       59.94  
DP1 disconnected (normal left inverted right x axis y axis)
HDMI1 disconnected (normal left inverted right x axis y axis)
HDMI2 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
0 ✓ kdex@punchy ~ $ 
``

**Comment by martin-ueding** [comment]
Then add the following to `~/.config/thinkpad-scripts/config.ini`:

```ini
[screen]
internal = eDP1
```

With that it should work.

**Comment by kdex** [comment]
This worked. However, the output is completely scrambled up. See #91 for more information.

**Comment by jturner314** [comment]
This error also occurs when two external displays (e.g. `VGA1` and `HDMI2`) are enabled and the internal one (`LVDS1`) is disabled.

**Comment by martin-ueding** [comment]
@jturner314, your pull request also closes this issue, then. Right?

**Comment by jturner314** [comment]
@martin-ueding Yes, #95 closes this issue on the martin-ueding:transformation-matrix branch.
